add_gimp_in_Install_Ubuntu_Mate_desktop
KBKN-Autonomous-Robotics-Lab/orange_ros2_docker pull request #26
Opened 2023-11-20 11:35 UTC by shunki1006

## 概要

- 画像編集ソフト(gimp)インストールの自動化. 

### なぜこのタスクを行うのか

- 現在, 環境地図のクリーンアップにgimpを使用しているが, 使用前にWiFi環境下でインストールする必要があり手間だから. 
- 特に屋外での作業時に不便だと感じた. 

### やったこと

- Dockerfile内のInstall Ubuntu Mate desktop内にgimpを追記した. 

### できるようになること

- dockerからイメージを入れた時点でインストール作業なくgimpを利用できるようになる. 

### できなくなること

- なし.

2023-11-20 12:45 UTC, shunki1006 commented
本PRの変更点の実機動作確認終了しました. 
コンテナ開いてすぐにgimpでmap.pgm開けたので問題ないと思います. 
レビューお願いいたします.

2023-11-20 12:52 UTC, Alpaca-zip requested changes
terminator、firefox、vscodeは以下でデスクトップ上にショートカットを作るようにしているので、gimpに関しても同様にデスクトップにショートカットを置いてもらえると助かります。

https://github.com/KBKN-Autonomous-Robotics-Lab/orange_ros2_docker/blob/83b3bbf5c2bd251c31f968814c5c765c55d0dda6/entrypoint.sh#L75-#L128

2023-11-20 12:52 UTC, Alpaca-zip commented on Dockerfile
> +    gimp && \
gimpのインストールする位置ですが、以下に合わせてもらいたいです。

https://github.com/KBKN-Autonomous-Robotics-Lab/orange_ros2_docker/blob/83b3bbf5c2bd251c31f968814c5c765c55d0dda6/Dockerfile#L39

2023-11-21 09:53 UTC, shunki1006 commented
> terminator、firefox、vscodeは以下でデスクトップ上にショートカットを作るようにしているので、gimpに関しても同様にデスクトップにショートカットを置いてもらえると助かります。
> 
> https://github.com/KBKN-Autonomous-Robotics-Lab/orange_ros2_docker/blob/83b3bbf5c2bd251c31f968814c5c765c55d0dda6/entrypoint.sh#L75-#L128

ご指定の通り, installの位置をfirefoxなどと合わせました. 
また, Desktopからも使えることを確認しました. ![スクリーンショット 2023-11-21 18 49 07](https://github.com/KBKN-Autonomous-Robotics-Lab/orange_ros2_docker/assets/88425011/a091c20a-a5b3-4668-a6cf-ecf043574d63)

2023-11-21 09:54 UTC, Alpaca-zip approved these changes
良いと思います。ありがとうございます。

2023-11-21 09:54 UTC, merged